inherit_from: .rails-rubocop.yml

AllCops:
  Exclude:
    - 'test/**/*'
    - 'lib/active_merchant/**/*'
    - 'bin/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
